In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv("50_Startups.csv")

In [3]:
dataset.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
dataset = pd.get_dummies(dataset,drop_first=True)
dataset = dataset.astype(int)

In [5]:
dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [6]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]
dependent = dataset[['Profit']]

In [8]:
independent.head()

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0     165349          136897           471784              0               1
1     162597          151377           443898              0               0
2     153441          101145           407934              1               0
3     144372          118671           383199              0               1
4     142107           91391           366168              1               0

In [9]:
dependent.head()

   Profit
0  192261
1  191792
2  191050
3  182901
4  166187

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(independent, dependent, test_size = 0.30, random_state=0)

In [11]:
#Standerdization i am going because to improve my model perforamnce
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
X_train

array([[ 1.17644918,  0.84516741,  0.94354831,  2.        , -0.76870611],
       [ 0.964209  ,  1.27283753,  0.42738466,  2.        , -0.76870611],
       [-1.47369376,  0.01533133, -1.52350767, -0.5       ,  1.30088727],
       [-1.48308111, -2.79556033, -1.53808904, -0.5       ,  1.30088727],
       [-0.14952413,  1.13638837, -0.71716479, -0.5       ,  1.30088727],
       [ 0.85311854, -0.04433364,  0.46771904, -0.5       ,  1.30088727],
       [-0.22353662, -0.31509692, -0.83981534,  2.        , -0.76870611],
       [-0.19455471,  0.21198893, -1.18497162, -0.5       , -0.76870611],
       [ 0.10479514, -0.08389031,  0.48741117, -0.5       , -0.76870611],
       [-1.00965537, -1.07020622, -0.40405994, -0.5       , -0.76870611],
       [ 0.06872149, -0.38396202,  0.75036622, -0.5       , -0.76870611],
       [-1.17639355,  0.14067823, -1.26581662, -0.5       ,  1.30088727],
       [ 0.97648634,  0.96892273,  0.84958544, -0.5       ,  1.30088727],
       [ 0.39131425,  0.45561766,  0.3979001 , -0.5       , -0.76870611],
       [-0.16881124,  0.6131456 , -0.48098184, -0.5       , -0.76870611],
       [ 1.20879249, -0.92948696,  1.24226335, -0.5       ,  1.30088727],
       [ 0.44593715,  0.82758236,  0.6270797 , -0.5       ,  1.30088727],
       [-0.9048368 , -0.20232741, -0.2140807 , -0.5       , -0.76870611],
       [-1.49419016, -0.26300168, -1.19195964, -0.5       , -0.76870611],
       [ 1.83846226,  1.07214274,  1.86319372, -0.5       , -0.76870611],
       [ 0.42966301,  0.13827145,  0.37625408,  2.        , -0.76870611],
       [-0.59093451, -2.81341712, -0.02839235, -0.5       , -0.76870611],
       [ 0.08493413, -0.95017754, -0.46096789, -0.5       ,  1.30088727],
       [ 1.26493212,  0.90991769, -0.55948984, -0.5       , -0.76870611],
       [-0.11002758, -0.69901791,  0.79713695,  2.        , -0.76870611],
       [-0.90670197,  0.1280232 ,  0.00300012,  2.        , -0.76870611],
       [ 0.11250179,  1.16515333,  0.75858788, -0.5       ,  1.30088727],
       [ 0.27708784,  1.15509918, -1.53808904, -0.5       ,  1.30088727],
       [ 1.03371228, -0.58535556,  0.79876902, -0.5       , -0.76870611],
       [-0.70389014, -1.58289019, -0.19719297, -0.5       , -0.76870611],
       [-1.4672374 , -0.30830358,  0.73848965,  2.        , -0.76870611],
       [ 1.46491545, -0.19747502,  1.39809935, -0.5       ,  1.30088727],
       [ 1.89486834,  0.51004205,  2.07686481, -0.5       ,  1.30088727],
       [-1.49419016,  0.45293914, -1.53808904, -0.5       , -0.76870611],
       [-1.03964159,  1.20525347, -1.32098523, -0.5       , -0.76870611]])

In [281]:
from sklearn.svm import SVR
regressor = SVR(kernel='linear', C=0.01) # rbf is radial bais function, Poly,sigmoid,linear
regressor.fit(X_train,y_train) # Model is created with this code

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=0.01, kernel='linear')

In [282]:
y_pred = regressor.predict(X_test)

In [283]:
bais = regressor.intercept_

In [284]:
bais

array([108732.98626668])

In [285]:
regressor.n_support_

array([34], dtype=int32)

In [286]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [287]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [288]:
r_score

-0.057474775703502345