In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset.head()
dataset = dataset.astype(int)

In [6]:
dataset.head()

   age  bmi  children  charges  sex_male  smoker_yes
0   19   27         0    16884         0           1
1   18   33         1     1725         1           0
2   28   33         3     4449         1           0
3   33   22         0    21984         1           0
4   32   28         0     3866         1           0

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [8]:
indep = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dept = dataset[['charges']]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep,dept,test_size=0.20,random_state=42)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid = { 'criterion':['absolute_error','squared_error'],'max_features':[None,'sqrt','log2'],'n_estimators':[10,100,]}
grid  = GridSearchCV(RandomForestRegressor(),param_grid, refit = True, verbose=3,n_jobs=-1)

grid.fit(indep,dept )

Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['absolute_error', 'squared_error'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [10]:
re = grid.cv_results_

#grid_predictions = grid.predict(X_test)
print('The R_score value for best parameter{}:'.format(grid.best_params_))

The R_score value for best parameter{'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.868917,0.203757,0.029893,0.035790,absolute_error,None,10,"{'criterion': 'absolute_error', 'max_features'...",0.829886,0.743197,0.848707,0.812624,0.825606,0.812004,0.036295,10
1,10.571044,1.299628,0.131973,0.015392,absolute_error,None,100,"{'criterion': 'absolute_error', 'max_features'...",0.831550,0.762090,0.854520,0.818982,0.836085,0.820645,0.031420,6
2,0.540311,0.057999,0.010279,0.002645,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.846721,0.746781,0.847770,0.814319,0.818924,0.814903,0.036741,8
3,6.973063,0.423492,0.151484,0.041650,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.860823,0.773427,0.853458,0.825854,0.841622,0.831037,0.031138,2
4,0.751305,0.022354,0.030331,0.037958,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.848194,0.744022,0.840155,0.809539,0.816261,0.811634,0.036735,11
5,7.219350,0.193052,0.153481,0.048578,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855688,0.778573,0.851768,0.828107,0.842005,0.831228,0.027995,1
6,0.334242,0.042620,0.027303,0.032023,squared_error,None,10,"{'criterion': 'squared_error', 'max_features':...",0.843513,0.729960,0.829379,0.807168,0.818952,0.805794,0.039761,12
7,2.950848,0.225854,0.154492,0.034436,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",0.841976,0.765459,0.856285,0.810084,0.831893,0.821139,0.031647,5
8,0.150398,0.071347,0.050558,0.051567,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.837807,0.755732,0.838391,0.806993,0.842687,0.816322,0.032869,7
9,1.394610,0.869184,0.092886,0.065414,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.851035,0.771529,0.850882,0.823076,0.837582,0.826821,0.029504,4
10,0.184552,0.110102,0.028036,0.036995,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.840784,0.751340,0.840349,0.817551,0.818814,0.813767,0.032782,9
11,1.356016,0.425607,0.056510,0.026407,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856276,0.768773,0.854407,0.821860,0.838360,0.827935,0.032093,3

In [13]:
age_input = float(input('Age:'))
bmi_input  = float(input('BMI:'))
Children_input = int(input('Children:'))
sex_male_input=int(input('Sex Male 0 or 1:'))
smoker_yes_input=int(input('smoker yes 0 or 1:'))

Age: 25
BMI: 32
Children: 2
Sex Male 0 or 1: 0
smoker yes 0 or 1: 1

In [14]:
Future_prediction =grid.predict([[age_input,bmi_input,Children_input,sex_male_input,smoker_yes_input]])
print("Future_prediction={}".format(Future_prediction))

Future_prediction=[36097.22]

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

#####