In [2]:
import pandas as pd

In [4]:
dataset = pd.read_csv('50_Startups.csv')

In [5]:
dataset .head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [9]:
dataset= pd.get_dummies(dataset,drop_first = True)
dataset = dataset.astype(int)

In [10]:
dataset.head()

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349,136897,471784,192261,0,1
1,162597,151377,443898,191792,0,0
2,153441,101145,407934,191050,1,0
3,144372,118671,383199,182901,0,1
4,142107,91391,366168,166187,1,0

In [11]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [12]:
Independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]
dependent = dataset[['Profit']]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(Independent ,dependent ,test_size = 0.20, random_state = 0)

In [206]:
X_train.head()

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
33      55493          103057           214634              1               0
35      46014           85047           205517              0               1
26      75328          144135           134050              1               0
34      46426          157693           210797              0               0
18      91749          114175           294919              1               0

In [197]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=358,criterion='squared_error',max_features=None,random_state=42)

In [198]:
regressor = regressor.fit(X_train,y_train)

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [199]:
y_pred = regressor.predict(X_test)

In [200]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [201]:
r_score

0.9652140512482825

In [202]:
import pickle
filename = 'Finalize_Model_RF.sav'

In [204]:
pickle.dump(regressor,open(filename, 'wb'))

In [205]:
loaded_model = pickle.load(open('Finalize_Model_RF.sav', 'rb'))

In [207]:
result = loaded_model.predict([[85328,154135,144050,1,0]])

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [208]:
result

array([127356.06703911])