In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset.head()

   age     sex     bmi  children smoker      charges
0   19  female  27.900         0    yes  16884.92400
1   18    male  33.770         1     no   1725.55230
2   28    male  33.000         3     no   4449.46200
3   33    male  22.705         0     no  21984.47061
4   32    male  28.880         0     no   3866.85520

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

# Convert categorical data to numerical
from sklearn.preprocessing import LabelEncoder

# Example dataset
data = {'Smoker': ['Yes', 'No', 'Yes', 'No', 'Yes']}
df = pd.DataFrame(data)

# Create label encoder object
le = LabelEncoder()

# Fit and transform the 'Smoker' column
df['Smoker'] = le.fit_transform(df['Smoker'])

print(df)

In [6]:
dataset = pd.get_dummies(dataset)
dataset = dataset.astype(int)

In [7]:
dataset.head()

   age  bmi  children  charges  sex_female  sex_male  smoker_no  smoker_yes
0   19   27         0    16884           1         0          0           1
1   18   33         1     1725           0         1          1           0
2   28   33         3     4449           0         1          1           0
3   33   22         0    21984           0         1          1           0
4   32   28         0     3866           0         1          1           0

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_no', 'smoker_yes'],
      dtype='object')

In [9]:
Independent = dataset[['age', 'bmi', 'children','sex_female', 'sex_male',
       'smoker_no', 'smoker_yes']]
Dependent = dataset[['charges']]

In [10]:
Independent.head()

   age  bmi  children  sex_female  sex_male  smoker_no  smoker_yes
0   19   27         0           1         0          0           1
1   18   33         1           0         1          1           0
2   28   33         3           0         1          1           0
3   33   22         0           0         1          1           0
4   32   28         0           0         1          1           0

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(Independent,Dependent,test_size = 0.30,random_state = 42)

In [12]:
# Linear regression

from sklearn.linear_model import LinearRegression
regressor1 = LinearRegression()
regressor1 = regressor1.fit(X_train,y_train)

In [13]:
y_pred = regressor1.predict(X_test)

In [14]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [15]:
r_score

0.7681647919672667

In [16]:
# SVR Regression

from sklearn.svm import SVR
regressor2 = SVR(kernel='sigmoid', C =5000)
regressor2 = regressor2.fit(X_train,y_train)
y_pred = regressor2.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

-23.586756248926093

In [17]:
# Decision Tree Regression

from sklearn.tree import DecisionTreeRegressor

regressor3 = DecisionTreeRegressor(criterion='poisson',splitter='best', max_features=None, random_state=0)
regressor3 = regressor3.fit(X_train,y_train)
y_pred = regressor3.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

0.7685195385899634

In [18]:
from sklearn.ensemble import RandomForestRegressor

regressor4 = RandomForestRegressor(n_estimators=100,criterion='poisson',random_state=42,max_features=None)
regressor4 = regressor4.fit(X_train,y_train)
y_pred = regressor4.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.841216778726616

class sklearn.ensemble.AdaBoostRegressor(estimator=None, *, n_estimators=50, learning_rate=1.0, loss='linear', random_state=None)[sou

In [33]:
from sklearn.ensemble import AdaBoostRegressor

regressor5 = AdaBoostRegressor(n_estimators=1,loss='linear',random_state=42)
regressor5 = regressor5.fit(X_train,y_train)
y_pred = regressor5.predict(X_test)
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8364623069554815

ada_params={
    "n_estimators":[50,60,70,80],
    "loss":['linear','square','exponential']
}

loss : {‘ls’, ‘lad’, ‘huber’, ‘quantile’}
n_estimators

In [76]:
from sklearn.ensemble import GradientBoostingRegressor
regressor6 = GradientBoostingRegressor(loss='huber',n_estimators =40,random_state=42)
regressor6 = regressor6.fit(X_train,y_train)
y_pred = regressor6.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score
result =r_score(y_test,y_pred)
print(result)

0.8716059242261023

C:\Users\gopi\Anaconda\envs\myenv\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

In [80]:
!pip install xgboost

Collecting xgboost
  Downloading xgboost-3.0.3-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\gopi\anaconda\envs\myenv\lib\site-packages (from xgboost) (2.2.5)
Requirement already satisfied: scipy in c:\users\gopi\anaconda\envs\myenv\lib\site-packages (from xgboost) (1.15.3)
Downloading xgboost-3.0.3-py3-none-win_amd64.whl (149.9 MB)
   ---------------------------------------- 0.0/149.9 MB ? eta -:--:--
   ---------------------------------------- 1.0/149.9 MB 6.7 MB/s eta 0:00:23
   ---------------------------------------- 1.8/149.9 MB 4.9 MB/s eta 0:00:31
    --------------------------------------- 2.1/149.9 MB 4.8 MB/s eta 0:00:32
    --------------------------------------- 3.4/149.9 MB 4.3 MB/s eta 0:00:34
   - -------------------------------------- 3.9/149.9 MB 4.1 MB/s eta 0:00:36
   - -------------------------------------- 4.7/149.9 MB 4.0 MB/s eta 0:00:37
   - -------------------------------------- 5.8/149.9 MB 4.1 MB/s eta 0:00:36
   - -------------------------------------- 6.6/149.9 MB 4.1 MB/s eta 0:00:36
   - -------------------------------------- 7.1/149.9 MB 4.0 MB/s eta 0:00:36
   -- ------------------------------------- 8.1/149.9 MB 4.0 MB/s eta 0:00:36
   -- ------------------------------------- 8.9/149.9 MB 4.0 MB/s eta 0:00:36
   -- ------------------------------------- 9.7/149.9 MB 4.0 MB/s eta 0:00:36
   -- ------------------------------------- 10.5/149.9 MB 4.0 MB/s eta 0:00:35
   --- ------------------------------------ 11.3/149.9 MB 4.0 MB/s eta 0:00:35
   --- ------------------------------------ 12.1/149.9 MB 4.0 MB/s eta 0:00:35
   --- ------------------------------------ 13.1/149.9 MB 4.0 MB/s eta 0:00:35
   --- ------------------------------------ 13.9/149.9 MB 4.0 MB/s eta 0:00:35
   --- ------------------------------------ 14.7/149.9 MB 4.0 MB/s eta 0:00:35
   ---- ----------------------------------- 15.5/149.9 MB 4.0 MB/s eta 0:00:35
   ---- ----------------------------------- 16.3/149.9 MB 4.0 MB/s eta 0:00:34
   ---- ----------------------------------- 17.0/149.9 MB 3.9 MB/s eta 0:00:34
   ---- ----------------------------------- 17.8/149.9 MB 3.9 MB/s eta 0:00:34
   ---- ----------------------------------- 18.6/149.9 MB 3.9 MB/s eta 0:00:34
   ----- ---------------------------------- 19.4/149.9 MB 3.9 MB/s eta 0:00:34
   ----- ---------------------------------- 20.4/149.9 MB 3.9 MB/s eta 0:00:33
   ----- ---------------------------------- 21.2/149.9 MB 3.9 MB/s eta 0:00:33
   ----- ---------------------------------- 22.0/149.9 MB 3.9 MB/s eta 0:00:33
   ------ --------------------------------- 22.8/149.9 MB 3.9 MB/s eta 0:00:33
   ------ --------------------------------- 23.6/149.9 MB 3.9 MB/s eta 0:00:33
   ------ --------------------------------- 24.4/149.9 MB 3.9 MB/s eta 0:00:32
   ------ --------------------------------- 25.4/149.9 MB 3.9 MB/s eta 0:00:32
   ------ --------------------------------- 26.2/149.9 MB 3.9 MB/s eta 0:00:32
   ------- -------------------------------- 27.0/149.9 MB 3.9 MB/s eta 0:00:32
   ------- -------------------------------- 27.8/149.9 MB 3.9 MB/s eta 0:00:32
   ------- -------------------------------- 28.6/149.9 MB 3.9 MB/s eta 0:00:32
   ------- -------------------------------- 29.4/149.9 MB 3.9 MB/s eta 0:00:31
   -------- ------------------------------- 30.1/149.9 MB 3.9 MB/s eta 0:00:31
   -------- ------------------------------- 30.9/149.9 MB 3.9 MB/s eta 0:00:31
   -------- ------------------------------- 31.7/149.9 MB 3.9 MB/s eta 0:00:31
   -------- ------------------------------- 32.5/149.9 MB 3.9 MB/s eta 0:00:31
   -------- ------------------------------- 33.3/149.9 MB 3.9 MB/s eta 0:00:30
   --------- ------------------------------ 34.1/149.9 MB 3.9 MB/s eta 0:00:30
   --------- ------------------------------ 34.9/149.9 MB 3.9 MB/s eta 0:00:30
   --------- ------------------------------ 35.9/149.9 MB 3.9 MB/s eta 0:00:30
   --------- ------------------------------ 36.7/149.9 MB 3.9 MB/s eta 0:00:30
   ---------- ----------------------------- 37.5/149.9 MB 3.9 MB/s eta 0:00:29
   ---------- ----------------------------- 38.3/149.9 MB 3.9 MB/s eta 0:00:29
   ---------- ----------------------------- 39.1/149.9 MB 3.9 MB/s eta 0:00:29
   ---------- ----------------------------- 39.8/149.9 MB 3.9 MB/s eta 0:00:29
   ---------- ----------------------------- 40.6/149.9 MB 3.9 MB/s eta 0:00:29
   ----------- ---------------------------- 41.4/149.9 MB 3.9 MB/s eta 0:00:28
   ----------- ---------------------------- 42.5/149.9 MB 3.9 MB/s eta 0:00:28
   ----------- ---------------------------- 43.3/149.9 MB 3.9 MB/s eta 0:00:28
   ----------- ---------------------------- 44.0/149.9 MB 3.9 MB/s eta 0:00:28
   ----------- ---------------------------- 44.8/149.9 MB 3.9 MB/s eta 0:00:28
   ------------ --------------------------- 45.6/149.9 MB 3.9 MB/s eta 0:00:27
   ------------ --------------------------- 46.4/149.9 MB 3.9 MB/s eta 0:00:27
   ------------ --------------------------- 47.2/149.9 MB 3.9 MB/s eta 0:00:27
   ------------ --------------------------- 48.0/149.9 MB 3.9 MB/s eta 0:00:27
   ------------- -------------------------- 48.8/149.9 MB 3.9 MB/s eta 0:00:26
   ------------- -------------------------- 49.5/149.9 MB 3.9 MB/s eta 0:00:26
   ------------- -------------------------- 50.3/149.9 MB 3.9 MB/s eta 0:00:26
   ------------- -------------------------- 51.1/149.9 MB 3.9 MB/s eta 0:00:26
   ------------- -------------------------- 51.9/149.9 MB 3.9 MB/s eta 0:00:26
   -------------- ------------------------- 52.7/149.9 MB 3.9 MB/s eta 0:00:25
   -------------- ------------------------- 53.7/149.9 MB 3.9 MB/s eta 0:00:25
   -------------- ------------------------- 54.5/149.9 MB 3.9 MB/s eta 0:00:25
   -------------- ------------------------- 55.3/149.9 MB 3.9 MB/s eta 0:00:25
   -------------- ------------------------- 56.1/149.9 MB 3.9 MB/s eta 0:00:25
   --------------- ------------------------ 56.9/149.9 MB 3.9 MB/s eta 0:00:24
   --------------- ------------------------ 57.7/149.9 MB 3.9 MB/s eta 0:00:24
   --------------- ------------------------ 58.5/149.9 MB 3.9 MB/s eta 0:00:24
   --------------- ------------------------ 59.5/149.9 MB 3.9 MB/s eta 0:00:24
   ---------------- ----------------------- 60.3/149.9 MB 3.9 MB/s eta 0:00:24
   ---------------- ----------------------- 61.1/149.9 MB 3.9 MB/s eta 0:00:23
   ---------------- ----------------------- 61.9/149.9 MB 3.9 MB/s eta 0:00:23
   ---------------- ----------------------- 62.7/149.9 MB 3.9 MB/s eta 0:00:23
   ---------------- ----------------------- 63.4/149.9 MB 3.9 MB/s eta 0:00:23
   ----------------- ---------------------- 64.2/149.9 MB 3.9 MB/s eta 0:00:23
   ----------------- ---------------------- 65.0/149.9 MB 3.9 MB/s eta 0:00:22
   ----------------- ---------------------- 65.8/149.9 MB 3.9 MB/s eta 0:00:22
   ----------------- ---------------------- 66.6/149.9 MB 3.9 MB/s eta 0:00:22
   ----------------- ---------------------- 67.4/149.9 MB 3.9 MB/s eta 0:00:22
   ------------------ --------------------- 68.2/149.9 MB 3.9 MB/s eta 0:00:22
   ------------------ --------------------- 69.2/149.9 MB 3.9 MB/s eta 0:00:21
   ------------------ --------------------- 70.0/149.9 MB 3.9 MB/s eta 0:00:21
   ------------------ --------------------- 70.8/149.9 MB 3.9 MB/s eta 0:00:21
   ------------------- -------------------- 71.6/149.9 MB 3.9 MB/s eta 0:00:21
   ------------------- -------------------- 72.4/149.9 MB 3.9 MB/s eta 0:00:20
   ------------------- -------------------- 73.1/149.9 MB 3.9 MB/s eta 0:00:20
   ------------------- -------------------- 73.9/149.9 MB 3.9 MB/s eta 0:00:20
   ------------------- -------------------- 74.7/149.9 MB 3.9 MB/s eta 0:00:20
   -------------------- ------------------- 75.2/149.9 MB 3.9 MB/s eta 0:00:20
   -------------------- ------------------- 75.5/149.9 MB 3.9 MB/s eta 0:00:20
   -------------------- ------------------- 75.8/149.9 MB 3.8 MB/s eta 0:00:20
   -------------------- ------------------- 76.0/149.9 MB 3.8 MB/s eta 0:00:20
   -------------------- ------------------- 76.3/149.9 MB 3.8 MB/s eta 0:00:20
   -------------------- ------------------- 76.3/149.9 MB 3.8 MB/s eta 0:00:20
   -------------------- ------------------- 76.5/149.9 MB 3.7 MB/s eta 0:00:20
   -------------------- ------------------- 76.5/149.9 MB 3.7 MB/s eta 0:00:20
   -------------------- ------------------- 76.8/149.9 MB 3.7 MB/s eta 0:00:20
   -------------------- ------------------- 77.3/149.9 MB 3.6 MB/s eta 0:00:21
   -------------------- ------------------- 77.9/149.9 MB 3.6 MB/s eta 0:00:20
   -------------------- ------------------- 78.1/149.9 MB 3.6 MB/s eta 0:00:20
   -------------------- ------------------- 78.1/149.9 MB 3.6 MB/s eta 0:00:20
   -------------------- ------------------- 78.4/149.9 MB 3.5 MB/s eta 0:00:21
   -------------------- ------------------- 78.6/149.9 MB 3.5 MB/s eta 0:00:21
   --------------------- ------------------ 78.9/149.9 MB 3.5 MB/s eta 0:00:21
   --------------------- ------------------ 79.4/149.9 MB 3.5 MB/s eta 0:00:21
   --------------------- ------------------ 79.7/149.9 MB 3.5 MB/s eta 0:00:21
   --------------------- ------------------ 80.0/149.9 MB 3.4 MB/s eta 0:00:21
   --------------------- ------------------ 80.0/149.9 MB 3.4 MB/s eta 0:00:21
   --------------------- ------------------ 80.2/149.9 MB 3.4 MB/s eta 0:00:21
   --------------------- ------------------ 80.5/149.9 MB 3.4 MB/s eta 0:00:21
   --------------------- ------------------ 81.0/149.9 MB 3.4 MB/s eta 0:00:21
   --------------------- ------------------ 81.0/149.9 MB 3.4 MB/s eta 0:00:21
   --------------------- ------------------ 81.3/149.9 MB 3.3 MB/s eta 0:00:21
   --------------------- ------------------ 81.5/149.9 MB 3.3 MB/s eta 0:00:21
   --------------------- ------------------ 82.3/149.9 MB 3.3 MB/s eta 0:00:21
   ---------------------- ----------------- 83.4/149.9 MB 3.3 MB/s eta 0:00:21
   ---------------------- ----------------- 84.4/149.9 MB 3.3 MB/s eta 0:00:20
   ---------------------- ----------------- 85.2/149.9 MB 3.3 MB/s eta 0:00:20
   ---------------------- ----------------- 86.0/149.9 MB 3.3 MB/s eta 0:00:20
   ----------------------- ---------------- 86.8/149.9 MB 3.3 MB/s eta 0:00:19
   ----------------------- ---------------- 87.6/149.9 MB 3.3 MB/s eta 0:00:19
   ----------------------- ---------------- 88.3/149.9 MB 3.3 MB/s eta 0:00:19
   ----------------------- ---------------- 89.4/149.9 MB 3.4 MB/s eta 0:00:19
   ------------------------ --------------- 90.2/149.9 MB 3.4 MB/s eta 0:00:18
   ------------------------ --------------- 91.0/149.9 MB 3.4 MB/s eta 0:00:18
   ------------------------ --------------- 91.8/149.9 MB 3.4 MB/s eta 0:00:18
   ------------------------ --------------- 92.5/149.9 MB 3.4 MB/s eta 0:00:18
   ------------------------ --------------- 93.3/149.9 MB 3.4 MB/s eta 0:00:17
   ------------------------- -------------- 94.1/149.9 MB 3.4 MB/s eta 0:00:17
   ------------------------- -------------- 94.9/149.9 MB 3.4 MB/s eta 0:00:17
   ------------------------- -------------- 95.7/149.9 MB 3.4 MB/s eta 0:00:17
   ------------------------- -------------- 96.5/149.9 MB 3.4 MB/s eta 0:00:16
   ------------------------- -------------- 97.3/149.9 MB 3.4 MB/s eta 0:00:16
   -------------------------- ------------- 98.0/149.9 MB 3.4 MB/s eta 0:00:16
   -------------------------- ------------- 99.1/149.9 MB 3.4 MB/s eta 0:00:15
   -------------------------- ------------- 99.9/149.9 MB 3.4 MB/s eta 0:00:15
   -------------------------- ------------- 100.7/149.9 MB 3.4 MB/s eta 0:00:15
   --------------------------- ------------ 101.4/149.9 MB 3.4 MB/s eta 0:00:15
   --------------------------- ------------ 102.2/149.9 MB 3.4 MB/s eta 0:00:14
   --------------------------- ------------ 103.0/149.9 MB 3.4 MB/s eta 0:00:14
   --------------------------- ------------ 103.8/149.9 MB 3.4 MB/s eta 0:00:14
   --------------------------- ------------ 104.6/149.9 MB 3.4 MB/s eta 0:00:14
   ---------------------------- ----------- 105.4/149.9 MB 3.4 MB/s eta 0:00:14
   ---------------------------- ----------- 106.2/149.9 MB 3.4 MB/s eta 0:00:13
   ---------------------------- ----------- 107.0/149.9 MB 3.4 MB/s eta 0:00:13
   ---------------------------- ----------- 107.7/149.9 MB 3.4 MB/s eta 0:00:13
   ----------------------------- ---------- 108.8/149.9 MB 3.4 MB/s eta 0:00:13
   ----------------------------- ---------- 109.6/149.9 MB 3.4 MB/s eta 0:00:12
   ----------------------------- ---------- 110.4/149.9 MB 3.4 MB/s eta 0:00:12
   ----------------------------- ---------- 111.1/149.9 MB 3.4 MB/s eta 0:00:12
   ----------------------------- ---------- 111.9/149.9 MB 3.4 MB/s eta 0:00:12
   ------------------------------ --------- 112.7/149.9 MB 3.4 MB/s eta 0:00:11
   ------------------------------ --------- 113.5/149.9 MB 3.4 MB/s eta 0:00:11
   ------------------------------ --------- 114.3/149.9 MB 3.4 MB/s eta 0:00:11
   ------------------------------ --------- 115.1/149.9 MB 3.4 MB/s eta 0:00:11
   ------------------------------ --------- 115.9/149.9 MB 3.4 MB/s eta 0:00:10
   ------------------------------- -------- 116.7/149.9 MB 3.4 MB/s eta 0:00:10
   ------------------------------- -------- 117.7/149.9 MB 3.4 MB/s eta 0:00:10
   ------------------------------- -------- 118.5/149.9 MB 3.4 MB/s eta 0:00:10
   ------------------------------- -------- 119.3/149.9 MB 3.4 MB/s eta 0:00:09
   -------------------------------- ------- 120.1/149.9 MB 3.4 MB/s eta 0:00:09
   -------------------------------- ------- 120.8/149.9 MB 3.4 MB/s eta 0:00:09
   -------------------------------- ------- 121.6/149.9 MB 3.4 MB/s eta 0:00:09
   -------------------------------- ------- 122.7/149.9 MB 3.4 MB/s eta 0:00:08
   -------------------------------- ------- 123.5/149.9 MB 3.4 MB/s eta 0:00:08
   --------------------------------- ------ 124.3/149.9 MB 3.4 MB/s eta 0:00:08
   --------------------------------- ------ 125.0/149.9 MB 3.4 MB/s eta 0:00:08
   --------------------------------- ------ 125.6/149.9 MB 3.4 MB/s eta 0:00:08
   --------------------------------- ------ 126.6/149.9 MB 3.4 MB/s eta 0:00:07
   --------------------------------- ------ 127.4/149.9 MB 3.4 MB/s eta 0:00:07
   ---------------------------------- ----- 128.2/149.9 MB 3.4 MB/s eta 0:00:07
   ---------------------------------- ----- 129.0/149.9 MB 3.4 MB/s eta 0:00:07
   ---------------------------------- ----- 129.8/149.9 MB 3.4 MB/s eta 0:00:06
   ---------------------------------- ----- 130.5/149.9 MB 3.4 MB/s eta 0:00:06
   ----------------------------------- ---- 131.3/149.9 MB 3.4 MB/s eta 0:00:06
   ----------------------------------- ---- 132.1/149.9 MB 3.4 MB/s eta 0:00:06
   ----------------------------------- ---- 133.2/149.9 MB 3.4 MB/s eta 0:00:05
   ----------------------------------- ---- 134.0/149.9 MB 3.4 MB/s eta 0:00:05
   ----------------------------------- ---- 134.7/149.9 MB 3.4 MB/s eta 0:00:05
   ------------------------------------ --- 135.5/149.9 MB 3.4 MB/s eta 0:00:05
   ------------------------------------ --- 136.3/149.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------------ --- 137.1/149.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------------ --- 137.9/149.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------------- -- 138.7/149.9 MB 3.4 MB/s eta 0:00:04
   ------------------------------------- -- 139.7/149.9 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 140.2/149.9 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 141.3/149.9 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 142.1/149.9 MB 3.4 MB/s eta 0:00:03
   -------------------------------------- - 142.9/149.9 MB 3.4 MB/s eta 0:00:03
   -------------------------------------- - 143.9/149.9 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 144.7/149.9 MB 3.4 MB/s eta 0:00:02
   -------------------------------------- - 145.5/149.9 MB 3.4 MB/s eta 0:00:02
   ---------------------------------------  146.3/149.9 MB 3.4 MB/s eta 0:00:02
   ---------------------------------------  147.1/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  147.8/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  148.6/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  149.4/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  149.7/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  149.7/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  149.7/149.9 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 149.9/149.9 MB 3.3 MB/s eta 0:00:00
Installing collected packages: xgboost
Successfully installed xgboost-3.0.3

In [118]:
from xgboost import XGBRegressor
regressor7 = XGBRegressor(learning_rate=0.05,n_estimators =60,random_state=42)
regressor7 = regressor7.fit(X_train,y_train)
y_pred = regressor7.predict(X_test)
from sklearn.metrics import r2_score
r_score=r2_score
result =r_score(y_test,y_pred)
print(result)

0.8620412945747375